spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogworld?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 994499
    driver-class-name: com.mysql.cj.jdbc.Driver