spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogworld?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 994499
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 152842488692-r6qog1424032shd2bmrkdkfd8953a47c.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 390373460055871
            client-secret: 7540714caed79642a0ea6e0b45ad54db
            scope:
              - email
              - public_profile

          naver:
            client-id: GsMNPfQO7Ocw17k8_i9Y
            client-secret: 2_2iTF_jh7
            scope:
              - name
              - email
#              - profile-image
            client-name: Naver
            authorization-grant-type: authorization_code
              #네이버는 주소가 고정이 안되어 있어서 맞춰주는 것이 편함 (facebook, google 등과)
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

          kakao :
            client-id: 6657fcb6243fa8e4523b7b27615b85ad
            client-secret: jdKH4v5u5KYtzNA6ybjh4SzOoor05U0W
            scope:
              - name
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원 정보를 json으로 받는데 response라는 키 값으로 보내줌

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 회원 정보를 json으로 받는데 response라는 키 값으로 보내줌

logging:
  level:
    org.hibernate.sql: debug

#server:
#  servlet:
#    session:
#      timeout: 10
#      cookie:
#        http-only: true
#        max-age: 10