spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogworld?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 994499
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#  security:
#    user:
#      password: 7d8e7dbf-f065-4694-a487-64b7aec11966

logging:
  level:
    org.hibernate.sql: debug

server:
  servlet:
    session:
      timeout: 10
      cookie:
        http-only: true
        max-age: 10